let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
basic.showString("Juan")
basic.forever(function () {
    basic.showLeds(`
        # # . # #
        # # . # #
        . . . . .
        # # # # #
        . . . . .
        `)
    music.rest(music.beat(BeatFraction.Double))
    music.playTone(523, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 255, 0))
    music.playTone(587, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(659, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(0, 0, 255))
    music.playTone(587, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 255, 255))
    music.playTone(523, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 255))
    music.playTone(587, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 255, 0))
    music.playTone(784, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(659, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 0, 255))
    music.playTone(784, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 255, 0))
    music.playTone(880, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(0, 255, 255))
    music.playTone(784, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 255))
    music.playTone(659, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 255, 0))
    music.playTone(523, music.beat(BeatFraction.Breve))
    strip.showColor(neopixel.rgb(0, 0, 255))
    music.playTone(523, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 255, 0))
    music.playTone(523, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 255))
    music.playTone(523, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 255, 0))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(0, 255, 255))
    music.playTone(523, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(20, 255, 75))
    music.playTone(587, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 100, 43))
    music.playTone(659, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(158, 32, 255))
    music.playTone(587, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(12, 255, 190))
    music.playTone(523, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 0, 255))
    music.playTone(523, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(523, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(100, 255, 23))
    music.playTone(523, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.rgb(255, 0, 0))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 200, 45))
    music.playTone(523, music.beat(BeatFraction.Breve))
    strip.showColor(neopixel.rgb(0, 100, 0))
})
